### ISSUE TITLE
Support More Languages

### ISSUE THREAD

**Issue by ZilvinasKucinskas** [sreekanthgs/bip_mnemonic#1]
The following word lists could be added as in [specification](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md)

Making the implementation extensible with additional word lists easily would be a super nice too :)

**Comment by sreekanthgs** [comment]
This has been introduced as of version 0.0.4. 
Also, adding new word lists are now easy. Add my_language.txt to words folder and pass language: my_language to supported methods.
